// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4JqhLKwHSwkMe51IoF1hCVvY0b8smuY',
    appId: '1:834367201092:web:3bfde7419cbfd7a0cf0111',
    messagingSenderId: '834367201092',
    projectId: 'han-eat',
    authDomain: 'han-eat.firebaseapp.com',
    storageBucket: 'han-eat.firebasestorage.app',
    measurementId: 'G-7VPTPJQSSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC99fIetu5nEz71-iLgheuA5U0aJJRO1Ww',
    appId: '1:834367201092:android:f13234698206e38acf0111',
    messagingSenderId: '834367201092',
    projectId: 'han-eat',
    storageBucket: 'han-eat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2YEEwYD36C_34Bq6Cb1AnDHuCSkV2tIg',
    appId: '1:834367201092:ios:0cf7c173a623be05cf0111',
    messagingSenderId: '834367201092',
    projectId: 'han-eat',
    storageBucket: 'han-eat.firebasestorage.app',
    iosBundleId: 'com.example.hanEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2YEEwYD36C_34Bq6Cb1AnDHuCSkV2tIg',
    appId: '1:834367201092:ios:0cf7c173a623be05cf0111',
    messagingSenderId: '834367201092',
    projectId: 'han-eat',
    storageBucket: 'han-eat.firebasestorage.app',
    iosBundleId: 'com.example.hanEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG4JqhLKwHSwkMe51IoF1hCVvY0b8smuY',
    appId: '1:834367201092:web:e766326dbfbaaac0cf0111',
    messagingSenderId: '834367201092',
    projectId: 'han-eat',
    authDomain: 'han-eat.firebaseapp.com',
    storageBucket: 'han-eat.firebasestorage.app',
    measurementId: 'G-E815K7H4DT',
  );
}
