"""add video_processing

Revision ID: 013_add_video_processing
Revises: 012_add_notification_preferences
Create Date: 2025-01-XX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013_add_video_processing'
down_revision = '012_add_notification_preferences'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(length=100), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('mp4_720p_url', sa.Text(), nullable=True),
    sa.Column('mp4_480p_url', sa.Text(), nullable=True),
    sa.Column('hls_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('original_duration', sa.Float(), nullable=True),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_processing_id'), 'video_processing', ['id'], unique=False)
    op.create_index(op.f('ix_video_processing_status'), 'video_processing', ['status'], unique=False)
    op.create_index(op.f('ix_video_processing_upload_id'), 'video_processing', ['upload_id'], unique=True)
    op.create_index(op.f('ix_video_processing_user_id'), 'video_processing', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_processing_created_at'), 'video_processing', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_processing_created_at'), table_name='video_processing')
    op.drop_index(op.f('ix_video_processing_user_id'), table_name='video_processing')
    op.drop_index(op.f('ix_video_processing_upload_id'), table_name='video_processing')
    op.drop_index(op.f('ix_video_processing_status'), table_name='video_processing')
    op.drop_index(op.f('ix_video_processing_id'), table_name='video_processing')
    op.drop_table('video_processing')
    # ### end Alembic commands ###

