"""add image_processing

Revision ID: 014_add_image_processing
Revises: 013_add_video_processing
Create Date: 2025-01-XX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014_add_image_processing'
down_revision = '013_add_video_processing'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(length=100), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('large_url', sa.Text(), nullable=True),
    sa.Column('medium_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('large_webp_url', sa.Text(), nullable=True),
    sa.Column('medium_webp_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_webp_url', sa.Text(), nullable=True),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('original_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_processing_id'), 'image_processing', ['id'], unique=False)
    op.create_index(op.f('ix_image_processing_status'), 'image_processing', ['status'], unique=False)
    op.create_index(op.f('ix_image_processing_upload_id'), 'image_processing', ['upload_id'], unique=True)
    op.create_index(op.f('ix_image_processing_user_id'), 'image_processing', ['user_id'], unique=False)
    op.create_index(op.f('ix_image_processing_created_at'), 'image_processing', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_processing_created_at'), table_name='image_processing')
    op.drop_index(op.f('ix_image_processing_user_id'), table_name='image_processing')
    op.drop_index(op.f('ix_image_processing_upload_id'), table_name='image_processing')
    op.drop_index(op.f('ix_image_processing_status'), table_name='image_processing')
    op.drop_index(op.f('ix_image_processing_id'), table_name='image_processing')
    op.drop_table('image_processing')
    # ### end Alembic commands ###

