"""Flex catalog: one feature per level, long messenger+ tail."""

BASE_PRICE_RUB = 39
LEVEL_STEP_RUB = 10
MIN_LEVEL = 1
MAX_LEVEL = 79

CORE_FEATURE_SLUGS = frozenset(
    {
        "ad_free",
        "premium_badge",
        "exclusive_reactions",
        "larger_uploads",
        "profile_decoration",
        "priority_reels_quality",
        "ai_recommendations",
        "ai_priority_speed",
        "offline_saved_posts",
        "creator_tools",
        "creator_badge",
        "creator_scheduled_posts",
        "creator_promotion",
        "creator_pinned",
        "creator_analytics",
        "advanced_stats",
        "priority_support",
        "pro",
    }
)

CATALOG_FEATURE_SLUGS = frozenset(
    {
        "ad_free",
        "premium_badge",
        "exclusive_reactions",
        "larger_uploads",
        "profile_decoration",
        "priority_reels_quality",
        "ai_recommendations",
        "ai_priority_speed",
        "offline_saved_posts",
        "creator_tools",
        "creator_badge",
        "creator_scheduled_posts",
        "creator_promotion",
        "creator_pinned",
        "creator_analytics",
        "advanced_stats",
        "priority_support",
        "pro",
        "chat_translation",
        "extra_pins",
        "privacy_plus",
        "extra_folders",
        "message_effects",
        "scheduled_messages",
        "chat_wallpaper",
        "story_viewers",
        "story_close_friends",
        "gif_search",
        "animated_stickers",
        "group_readers",
        "live_location",
        "silent_send",
        "chat_search",
        "poll_quiz",
        "video_notes",
        "no_forwards",
        "channel_post_search",
        "folder_filters",
        "folder_icons",
        "voice_to_text",
        "emoji_status",
        "checklist",
        "profile_colors",
        "any_emoji_reactions",
        "voice_privacy",
        "saved_tags",
        "archive_non_contacts",
        "story_stealth",
        "longer_stories",
        "premium_stickers",
        "call_privacy",
        "extra_pinned_chats",
        "story_download",
        "auto_translate",
        "chat_tags",
        "default_folder",
        "hide_forward",
        "read_timestamps",
        "edit_history",
        "gif_favorites",
        "story_archive",
        "story_tray_priority",
        "group_add_privacy",
        "folder_share",
        "story_caption_plus",
        "animated_avatar",
        "quick_replies",
        "business_greeting",
        "business_away",
        "business_hours",
        "business_location",
        "business_intro",
        "business_bot",
        "dm_privacy",
        "profile_website",
        "custom_emoji",
        "emoji_pack_publish",
        "sticker_pack_sell",
        "custom_emoji_reactions",
    }
)

DEFAULT_BLOCKS = (
    {
        "key": "A",
        "title": "Базовые функции",
        "min_level": 1,
        "max_level": 6,
        "sort_order": 1,
    },
    {
        "key": "B",
        "title": "Расширенные функции",
        "min_level": 7,
        "max_level": 9,
        "sort_order": 2,
    },
    {
        "key": "C",
        "title": "PRO",
        "min_level": 10,
        "max_level": 18,
        "sort_order": 3,
    },
    {
        "key": "D",
        "title": "Мессенджер+",
        "min_level": 19,
        "max_level": 23,
        "sort_order": 4,
    },
    {
        "key": "E",
        "title": "Ещё",
        "min_level": 24,
        "max_level": 27,
        "sort_order": 5,
    },
    {
        "key": "F",
        "title": "Медиа+",
        "min_level": 28,
        "max_level": 31,
        "sort_order": 6,
    },
    {
        "key": "G",
        "title": "Чат+",
        "min_level": 32,
        "max_level": 35,
        "sort_order": 7,
    },
    {
        "key": "H",
        "title": "Telegram+",
        "min_level": 36,
        "max_level": 39,
        "sort_order": 8,
    },
    {
        "key": "I",
        "title": "Премиум",
        "min_level": 40,
        "max_level": 43,
        "sort_order": 9,
    },
    {
        "key": "J",
        "title": "Ещё+",
        "min_level": 44,
        "max_level": 47,
        "sort_order": 10,
    },
    {
        "key": "K",
        "title": "Сторис+",
        "min_level": 48,
        "max_level": 51,
        "sort_order": 11,
    },
    {
        "key": "L",
        "title": "Входящие+",
        "min_level": 52,
        "max_level": 55,
        "sort_order": 12,
    },
    {
        "key": "M",
        "title": "Контроль",
        "min_level": 56,
        "max_level": 59,
        "sort_order": 13,
    },
    {
        "key": "N",
        "title": "Premium+",
        "min_level": 60,
        "max_level": 63,
        "sort_order": 14,
    },
    {
        "key": "O",
        "title": "Ещё Premium",
        "min_level": 64,
        "max_level": 67,
        "sort_order": 15,
    },
    {
        "key": "P",
        "title": "Бизнес",
        "min_level": 68,
        "max_level": 71,
        "sort_order": 16,
    },
    {
        "key": "Q",
        "title": "Ещё бизнес",
        "min_level": 72,
        "max_level": 75,
        "sort_order": 17,
    },
    {
        "key": "R",
        "title": "Магазин",
        "min_level": 76,
        "max_level": 79,
        "sort_order": 18,
    },
)

DEFAULT_FEATURES = (
    {
        "slug": "ad_free",
        "title": "Без рекламы",
        "description": "Лента и каналы без промо-вставок.",
        "icon": "block",
        "default_level": 1,
        "min_level": 1,
        "max_level": 1,
        "feature_type": "fixed",
        "movable": False,
        "required": True,
        "block_key": "A",
    },
    {
        "slug": "premium_badge",
        "title": "Значок подписчика",
        "description": "Отметка в профиле, что есть платная подписка.",
        "icon": "verified",
        "default_level": 2,
        "min_level": 1,
        "max_level": 6,
        "feature_type": "movable",
        "movable": True,
        "required": False,
        "block_key": "A",
    },
    {
        "slug": "exclusive_reactions",
        "title": "Эксклюзивные реакции",
        "description": "Дополнительные реакции в чатах и на постах.",
        "icon": "favorite",
        "default_level": 3,
        "min_level": 1,
        "max_level": 6,
        "feature_type": "movable",
        "movable": True,
        "required": False,
        "block_key": "A",
    },
    {
        "slug": "larger_uploads",
        "title": "Большие загрузки",
        "description": "Выше лимит размера фото, видео и файлов.",
        "icon": "cloud_upload",
        "default_level": 4,
        "min_level": 1,
        "max_level": 6,
        "feature_type": "movable",
        "movable": True,
        "required": False,
        "block_key": "A",
    },
    {
        "slug": "profile_decoration",
        "title": "Оформление профиля",
        "description": "Рамка аватара и оформление карточки профиля.",
        "icon": "palette",
        "default_level": 5,
        "min_level": 1,
        "max_level": 6,
        "feature_type": "movable",
        "movable": True,
        "required": False,
        "block_key": "A",
    },
    {
        "slug": "priority_reels_quality",
        "title": "Качество рилсов",
        "description": "Приоритет более чёткого видео в рилсах.",
        "icon": "hd",
        "default_level": 6,
        "min_level": 1,
        "max_level": 6,
        "feature_type": "movable",
        "movable": True,
        "required": False,
        "block_key": "A",
    },
    {
        "slug": "ai_recommendations",
        "title": "AI-рекомендации",
        "description": "Умная лента и подсказки, что смотреть дальше.",
        "icon": "auto_awesome",
        "default_level": 7,
        "min_level": 7,
        "max_level": 9,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "B",
    },
    {
        "slug": "ai_priority_speed",
        "title": "Приоритет AI",
        "description": "Быстрее ответы ассистента и переводчика.",
        "icon": "bolt",
        "default_level": 8,
        "min_level": 7,
        "max_level": 9,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "B",
    },
    {
        "slug": "offline_saved_posts",
        "title": "Офлайн-сохранёнки",
        "description": "Сохранённые посты доступны без сети.",
        "icon": "offline_pin",
        "default_level": 9,
        "min_level": 7,
        "max_level": 9,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "B",
    },
    {
        "slug": "creator_tools",
        "title": "Инструменты автора",
        "description": "Панель автора и закрытые каналы.",
        "icon": "handyman",
        "default_level": 10,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "premium",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "creator_badge",
        "title": "Бейдж автора",
        "description": "Оформление и бейдж канала.",
        "icon": "workspace_premium",
        "default_level": 11,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "creator_scheduled_posts",
        "title": "Отложенные посты",
        "description": "Публикация по расписанию в каналах.",
        "icon": "schedule",
        "default_level": 12,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "creator_promotion",
        "title": "Продвижение постов",
        "description": "Продвижение публикаций в каналах.",
        "icon": "campaign",
        "default_level": 13,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "creator_pinned",
        "title": "Закрепление постов",
        "description": "Закрепление важных публикаций в канале.",
        "icon": "push_pin",
        "default_level": 14,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "creator_analytics",
        "title": "Аналитика автора",
        "description": "Расширенная статистика каналов и постов.",
        "icon": "insights",
        "default_level": 15,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "advanced_stats",
        "title": "Расширенная статистика",
        "description": "Подробная статистика каналов и контента.",
        "icon": "query_stats",
        "default_level": 16,
        "min_level": 10,
        "max_level": 16,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "C",
    },
    {
        "slug": "priority_support",
        "title": "Приоритетная поддержка",
        "description": "Обращения обрабатываются вне общей очереди.",
        "icon": "support_agent",
        "default_level": 17,
        "min_level": 17,
        "max_level": 17,
        "feature_type": "fixed",
        "movable": False,
        "required": True,
        "block_key": "C",
    },
    {
        "slug": "pro",
        "title": "Полный доступ Pro",
        "description": "Все базовые, AI и авторские функции этой лестницы.",
        "icon": "diamond",
        "default_level": 18,
        "min_level": 18,
        "max_level": 18,
        "feature_type": "fixed",
        "movable": False,
        "required": True,
        "block_key": "C",
    },
    {
        "slug": "chat_translation",
        "title": "Перевод сообщений",
        "description": "Перевод текста в чатах на нужный язык.",
        "icon": "translate",
        "default_level": 19,
        "min_level": 19,
        "max_level": 23,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "D",
    },
    {
        "slug": "extra_pins",
        "title": "Больше закрепов",
        "description": "До 20 закреплённых сообщений в чате вместо пяти.",
        "icon": "push_pin",
        "default_level": 20,
        "min_level": 19,
        "max_level": 23,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "D",
    },
    {
        "slug": "privacy_plus",
        "title": "Приватность last seen",
        "description": "Скрывайте свой статус и всё равно видите, кто в сети. У кого уровень выше — всё равно видит вас.",
        "icon": "visibility_off",
        "default_level": 21,
        "min_level": 19,
        "max_level": 23,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "D",
    },
    {
        "slug": "extra_folders",
        "title": "Больше папок",
        "description": "До 50 папок чатов вместо десяти.",
        "icon": "folder",
        "default_level": 22,
        "min_level": 19,
        "max_level": 23,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "D",
    },
    {
        "slug": "message_effects",
        "title": "Эффекты сообщений",
        "description": "Конфетти, фейерверк и праздник при отправке.",
        "icon": "celebration",
        "default_level": 23,
        "min_level": 19,
        "max_level": 23,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "D",
    },
    {
        "slug": "scheduled_messages",
        "title": "Отложенные сообщения",
        "description": "Отправка в чат по расписанию или когда собеседник будет в сети.",
        "icon": "schedule_send",
        "default_level": 24,
        "min_level": 24,
        "max_level": 27,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "E",
    },
    {
        "slug": "chat_wallpaper",
        "title": "Обои и оформление чата",
        "description": "Свои фото-обои и пресеты Сумерки, Лес, Песок, Ночь.",
        "icon": "wallpaper",
        "default_level": 25,
        "min_level": 24,
        "max_level": 27,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "E",
    },
    {
        "slug": "story_viewers",
        "title": "Кто смотрел сторис",
        "description": "Список просмотров ваших сторис.",
        "icon": "visibility",
        "default_level": 26,
        "min_level": 24,
        "max_level": 27,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "E",
    },
    {
        "slug": "story_close_friends",
        "title": "Сторис для близких",
        "description": "Публикация сторис только для списка близких.",
        "icon": "favorite",
        "default_level": 27,
        "min_level": 24,
        "max_level": 27,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "E",
    },
    {
        "slug": "gif_search",
        "title": "Поиск GIF",
        "description": "Каталог и поиск GIF в чатах.",
        "icon": "gif",
        "default_level": 28,
        "min_level": 28,
        "max_level": 31,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "F",
    },
    {
        "slug": "animated_stickers",
        "title": "Анимированные стикеры",
        "description": "Добавление анимированных стикеров в свои паки.",
        "icon": "animation",
        "default_level": 29,
        "min_level": 28,
        "max_level": 31,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "F",
    },
    {
        "slug": "group_readers",
        "title": "Кто прочитал",
        "description": "Список прочтений ваших сообщений в группах.",
        "icon": "done_all",
        "default_level": 30,
        "min_level": 28,
        "max_level": 31,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "F",
    },
    {
        "slug": "live_location",
        "title": "Трансляция геопозиции",
        "description": "Делитесь живой геопозицией в чате.",
        "icon": "my_location",
        "default_level": 31,
        "min_level": 28,
        "max_level": 31,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "F",
    },
    {
        "slug": "silent_send",
        "title": "Отправка без звука",
        "description": "Сообщение доставляется без push-уведомления.",
        "icon": "notifications_off",
        "default_level": 32,
        "min_level": 32,
        "max_level": 35,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "G",
    },
    {
        "slug": "chat_search",
        "title": "Поиск по сообщениям",
        "description": "Поиск по тексту, дате и типу сообщений во всех чатах.",
        "icon": "search",
        "default_level": 33,
        "min_level": 32,
        "max_level": 35,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "G",
    },
    {
        "slug": "poll_quiz",
        "title": "Викторины и опросы+",
        "description": "Викторина, несколько ответов, таймер и скрытые результаты.",
        "icon": "quiz",
        "default_level": 34,
        "min_level": 32,
        "max_level": 35,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "G",
    },
    {
        "slug": "video_notes",
        "title": "Видеосообщения",
        "description": "Кружочки — короткие круглые видео в чате.",
        "icon": "videocam",
        "default_level": 35,
        "min_level": 32,
        "max_level": 35,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "G",
    },
    {
        "slug": "no_forwards",
        "title": "Запрет пересылки",
        "description": "Защита контента группы: нельзя пересылать и сохранять сообщения.",
        "icon": "lock",
        "default_level": 36,
        "min_level": 36,
        "max_level": 39,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "H",
    },
    {
        "slug": "channel_post_search",
        "title": "Поиск по каналу",
        "description": "Поиск постов внутри канала по тексту, тегам и рецепту.",
        "icon": "travel_explore",
        "default_level": 37,
        "min_level": 36,
        "max_level": 39,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "H",
    },
    {
        "slug": "folder_filters",
        "title": "Умные папки",
        "description": "Автосбор папки: контакты, боты, непрочитанные, без архива.",
        "icon": "filter_alt",
        "default_level": 38,
        "min_level": 36,
        "max_level": 39,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "H",
    },
    {
        "slug": "folder_icons",
        "title": "Эмодзи папок",
        "description": "Своя иконка-эмодзи у папки чатов, как в Telegram Premium.",
        "icon": "emoji_emotions",
        "default_level": 39,
        "min_level": 36,
        "max_level": 39,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "H",
    },
    {
        "slug": "voice_to_text",
        "title": "Голос в текст",
        "description": "Расшифровка голосовых и кружков, как в Telegram Premium.",
        "icon": "hearing",
        "default_level": 40,
        "min_level": 40,
        "max_level": 43,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "I",
    },
    {
        "slug": "emoji_status",
        "title": "Emoji-статус",
        "description": "Эмодзи рядом с именем в чатах и профиле.",
        "icon": "mood",
        "default_level": 41,
        "min_level": 40,
        "max_level": 43,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "I",
    },
    {
        "slug": "checklist",
        "title": "Чеклисты",
        "description": "Списки дел в чате: пункты можно отмечать вместе.",
        "icon": "checklist",
        "default_level": 42,
        "min_level": 40,
        "max_level": 43,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "I",
    },
    {
        "slug": "profile_colors",
        "title": "Цвет профиля",
        "description": "Цвет имени в списке чатов и в профиле.",
        "icon": "palette",
        "default_level": 43,
        "min_level": 40,
        "max_level": 43,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "I",
    },
    {
        "slug": "any_emoji_reactions",
        "title": "Любые реакции",
        "description": "Реакция любым эмодзи, не только из короткой панели.",
        "icon": "emoji_emotions",
        "default_level": 44,
        "min_level": 44,
        "max_level": 47,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "J",
    },
    {
        "slug": "voice_privacy",
        "title": "Кто шлёт голос",
        "description": "Ограничить голосовые и кружки: все, контакты или никто.",
        "icon": "mic_off",
        "default_level": 45,
        "min_level": 44,
        "max_level": 47,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "J",
    },
    {
        "slug": "saved_tags",
        "title": "Теги в Избранном",
        "description": "Метки для сообщений в Избранном, как в Telegram Premium.",
        "icon": "sell",
        "default_level": 46,
        "min_level": 44,
        "max_level": 47,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "J",
    },
    {
        "slug": "archive_non_contacts",
        "title": "Архив незнакомцев",
        "description": "Новые чаты не из контактов сразу в архив и без звука.",
        "icon": "inventory_2",
        "default_level": 47,
        "min_level": 44,
        "max_level": 47,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "J",
    },
    {
        "slug": "story_stealth",
        "title": "Скрытый просмотр",
        "description": "Смотреть сторис, не попадая в список просмотров.",
        "icon": "visibility_off",
        "default_level": 48,
        "min_level": 48,
        "max_level": 51,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "K",
    },
    {
        "slug": "longer_stories",
        "title": "Длинные сторис",
        "description": "Видео до 60 секунд и сторис на 48 часов, как в Telegram Premium.",
        "icon": "timelapse",
        "default_level": 49,
        "min_level": 48,
        "max_level": 51,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "K",
    },
    {
        "slug": "premium_stickers",
        "title": "Премиум-стикеры",
        "description": "Ставить и отправлять эксклюзивные стикерпаки.",
        "icon": "auto_awesome",
        "default_level": 50,
        "min_level": 48,
        "max_level": 51,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "K",
    },
    {
        "slug": "call_privacy",
        "title": "Кто звонит",
        "description": "Ограничить входящие звонки: все, контакты или никто.",
        "icon": "phone_disabled",
        "default_level": 51,
        "min_level": 48,
        "max_level": 51,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "K",
    },
    {
        "slug": "extra_pinned_chats",
        "title": "Больше закрепов в ленте",
        "description": "До 20 закреплённых чатов во входящих вместо пяти.",
        "icon": "push_pin",
        "default_level": 52,
        "min_level": 52,
        "max_level": 55,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "L",
    },
    {
        "slug": "story_download",
        "title": "Сохранить сторис",
        "description": "Скачать сторис в галерею, как в Telegram Premium.",
        "icon": "download",
        "default_level": 53,
        "min_level": 52,
        "max_level": 55,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "L",
    },
    {
        "slug": "auto_translate",
        "title": "Автоперевод чата",
        "description": "Сразу переводить входящие сообщения в выбранном чате.",
        "icon": "translate",
        "default_level": 54,
        "min_level": 52,
        "max_level": 55,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "L",
    },
    {
        "slug": "chat_tags",
        "title": "Метки чатов",
        "description": "Цветные метки на чатах и фильтр входящих, как в Telegram Premium.",
        "icon": "label",
        "default_level": 55,
        "min_level": 52,
        "max_level": 55,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "L",
    },
    {
        "slug": "default_folder",
        "title": "Папка при запуске",
        "description": "Сразу открывать выбранную папку вместо общего списка чатов.",
        "icon": "folder_special",
        "default_level": 56,
        "min_level": 56,
        "max_level": 59,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "M",
    },
    {
        "slug": "hide_forward",
        "title": "Пересылка без автора",
        "description": "Переслать сообщение как копию — без подписи «Переслано от…».",
        "icon": "content_copy",
        "default_level": 57,
        "min_level": 56,
        "max_level": 59,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "M",
    },
    {
        "slug": "read_timestamps",
        "title": "Время прочтения",
        "description": "Точное время, когда собеседник прочитал ваши сообщения.",
        "icon": "schedule",
        "default_level": 58,
        "min_level": 56,
        "max_level": 59,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "M",
    },
    {
        "slug": "edit_history",
        "title": "История правок",
        "description": "Посмотреть предыдущие версии изменённого сообщения.",
        "icon": "history",
        "default_level": 59,
        "min_level": 56,
        "max_level": 59,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "M",
    },
    {
        "slug": "gif_favorites",
        "title": "Избранные GIF",
        "description": "Сохранять GIF в облако и вставлять их с любого устройства.",
        "icon": "favorite",
        "default_level": 60,
        "min_level": 60,
        "max_level": 63,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "N",
    },
    {
        "slug": "story_archive",
        "title": "Архив сторис",
        "description": "Свои истёкшие сторис остаются в архиве, а не исчезают.",
        "icon": "inventory_2",
        "default_level": 61,
        "min_level": 60,
        "max_level": 63,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "N",
    },
    {
        "slug": "story_tray_priority",
        "title": "Приоритет сторис",
        "description": "Ваши сторис показываются выше в ленте у других.",
        "icon": "trending_up",
        "default_level": 62,
        "min_level": 60,
        "max_level": 63,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "N",
    },
    {
        "slug": "group_add_privacy",
        "title": "Кто добавляет в группы",
        "description": "Ограничить, кто может добавлять вас в группы: все, контакты или никто.",
        "icon": "group_off",
        "default_level": 63,
        "min_level": 60,
        "max_level": 63,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "N",
    },
    {
        "slug": "folder_share",
        "title": "Поделиться папкой",
        "description": "Отправить ссылку на папку чатов — получатель импортирует её себе.",
        "icon": "share",
        "default_level": 64,
        "min_level": 64,
        "max_level": 67,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "O",
    },
    {
        "slug": "story_caption_plus",
        "title": "Длинные подписи сторис",
        "description": "Подпись к сторис до 1000 символов вместо 500.",
        "icon": "notes",
        "default_level": 65,
        "min_level": 64,
        "max_level": 67,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "O",
    },
    {
        "slug": "animated_avatar",
        "title": "Анимированный аватар",
        "description": "Поставить GIF как фото профиля — оно будет двигаться.",
        "icon": "gif",
        "default_level": 66,
        "min_level": 64,
        "max_level": 67,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "O",
    },
    {
        "slug": "quick_replies",
        "title": "Быстрые ответы",
        "description": "Заготовки текста над полем ввода — вставить одним нажатием.",
        "icon": "quickreply",
        "default_level": 67,
        "min_level": 64,
        "max_level": 67,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "O",
    },
    {
        "slug": "business_greeting",
        "title": "Приветствие",
        "description": "Автоответ тем, кто пишет вам впервые или после паузы.",
        "icon": "waving_hand",
        "default_level": 68,
        "min_level": 68,
        "max_level": 71,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "P",
    },
    {
        "slug": "business_away",
        "title": "Меня нет",
        "description": "Автоответ, пока выключили приём или вне часов работы.",
        "icon": "beach_access",
        "default_level": 69,
        "min_level": 68,
        "max_level": 71,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "P",
    },
    {
        "slug": "business_hours",
        "title": "Часы работы",
        "description": "Расписание на профиле: открыто или закрыто прямо сейчас.",
        "icon": "schedule",
        "default_level": 70,
        "min_level": 68,
        "max_level": 71,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "P",
    },
    {
        "slug": "business_location",
        "title": "Адрес на карте",
        "description": "Точка и адрес в профиле — открывается в картах.",
        "icon": "place",
        "default_level": 71,
        "min_level": 68,
        "max_level": 71,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "P",
    },
    {
        "slug": "business_intro",
        "title": "Стартовая страница",
        "description": "Заголовок и текст интро в профиле, как у Telegram Business.",
        "icon": "web_stories",
        "default_level": 72,
        "min_level": 72,
        "max_level": 75,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "Q",
    },
    {
        "slug": "business_bot",
        "title": "Бот поддержки",
        "description": "Привязать своего бота к профилю — клиент пишет ему в один тап.",
        "icon": "smart_toy",
        "default_level": 73,
        "min_level": 72,
        "max_level": 75,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "Q",
    },
    {
        "slug": "dm_privacy",
        "title": "Кто пишет первым",
        "description": "Кто может начать с вами новый личный чат: все, контакты или никто.",
        "icon": "mail_lock",
        "default_level": 74,
        "min_level": 72,
        "max_level": 75,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "Q",
    },
    {
        "slug": "profile_website",
        "title": "Сайт в профиле",
        "description": "Ссылка на сайт или соцсеть под описанием профиля.",
        "icon": "link",
        "default_level": 75,
        "min_level": 72,
        "max_level": 75,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "Q",
    },
    {
        "slug": "custom_emoji",
        "title": "Свои эмодзи",
        "description": "Вставлять купленные кастомные эмодзи прямо в текст сообщений.",
        "icon": "emoji_emotions",
        "default_level": 76,
        "min_level": 76,
        "max_level": 79,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "R",
    },
    {
        "slug": "emoji_pack_publish",
        "title": "Продажа эмодзи",
        "description": "Выложить свой пак кастомных эмодзи в магазин и получать Stars за покупки.",
        "icon": "storefront",
        "default_level": 77,
        "min_level": 76,
        "max_level": 79,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "R",
    },
    {
        "slug": "sticker_pack_sell",
        "title": "Продажа стикеров",
        "description": "Выставить стикерпак на витрину за Stars — площадка берёт комиссию 5%.",
        "icon": "sell",
        "default_level": 78,
        "min_level": 76,
        "max_level": 79,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "R",
    },
    {
        "slug": "custom_emoji_reactions",
        "title": "Реакции своими эмодзи",
        "description": "Ставить реакции кастомными эмодзи из купленных паков.",
        "icon": "add_reaction",
        "default_level": 79,
        "min_level": 76,
        "max_level": 79,
        "feature_type": "blocked",
        "movable": True,
        "required": False,
        "block_key": "R",
    },
)

